[2025-08-08 17:25:29,682: INFO: main: Welcome to our Custom log]
[2025-08-09 11:11:25,447: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-08-09 11:11:25,447: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-09 11:11:25,463: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-09 11:11:25,463: ERROR: main: yaml file is empty]
Traceback (most recent call last):
  File "C:\Users\ramesh\Deep learning proj\Kidney_Disease_Classification_Deep_learning\src\cnnClassifier\utils\common.py", line 34, in read_yaml
    return ConfigBox(content)
  File "box\box.py", line 247, in box.box.Box.__init__
box.exceptions.BoxValueError: Cannot extrapolate Box from string

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 8, in <module>
    data_ingestion.main()
  File "C:\Users\ramesh\Deep learning proj\Kidney_Disease_Classification_Deep_learning\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 13, in main
    config = ConfigurationManager()
  File "C:\Users\ramesh\Deep learning proj\Kidney_Disease_Classification_Deep_learning\src\cnnClassifier\config\configuration.py", line 14, in __init__
    self.params = read_yaml(params_filepath)
  File "C:\Users\ramesh\anaconda3\envs\kidney\lib\site-packages\ensure\main.py", line 849, in __call__
    return_val = self.f(*args, **kwargs)
  File "C:\Users\ramesh\Deep learning proj\Kidney_Disease_Classification_Deep_learning\src\cnnClassifier\utils\common.py", line 36, in read_yaml
    raise ValueError("yaml file is empty")
ValueError: yaml file is empty
[2025-08-09 11:13:38,542: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-08-09 11:13:38,542: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-09 11:13:38,558: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-09 11:13:38,558: INFO: common: created directory at: artifacts]
[2025-08-09 11:13:38,558: INFO: common: created directory at: artifacts/data_ingestion]
[2025-08-09 11:13:38,558: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-08-09 11:13:49,307: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-08-09 11:13:52,104: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-08-09 12:13:20,602: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-08-09 12:13:20,610: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-09 12:13:20,618: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-09 12:13:20,618: INFO: common: created directory at: artifacts]
[2025-08-09 12:13:20,618: INFO: common: created directory at: artifacts/data_ingestion]
[2025-08-09 12:13:20,618: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-08-09 12:13:31,938: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-08-09 12:13:37,753: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-08-09 12:13:37,768: INFO: main: *******************]
[2025-08-09 12:13:37,768: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-08-09 12:13:37,784: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-09 12:13:37,800: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-09 12:13:37,831: INFO: common: created directory at: artifacts]
[2025-08-09 12:13:37,831: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-08-09 12:13:53,385: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-08-09 12:13:57,638: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-08-09 14:22:59,852: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-08-09 14:22:59,863: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-09 14:22:59,868: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-09 14:22:59,876: INFO: common: created directory at: artifacts]
[2025-08-09 14:22:59,878: INFO: common: created directory at: artifacts/data_ingestion]
[2025-08-09 14:22:59,883: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-08-09 14:23:11,008: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-08-09 14:23:12,663: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-08-09 14:23:12,668: INFO: main: *******************]
[2025-08-09 14:23:12,668: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-08-09 14:23:12,673: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-09 14:23:12,683: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-09 14:23:12,683: INFO: common: created directory at: artifacts]
[2025-08-09 14:23:12,688: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-08-09 14:23:14,225: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-08-09 14:23:15,349: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-08-09 14:23:15,351: INFO: main: *******************]
[2025-08-09 14:23:15,351: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-08-09 14:23:15,362: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-09 14:23:15,364: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-09 14:23:15,370: INFO: common: created directory at: artifacts]
[2025-08-09 14:23:15,373: INFO: common: created directory at: artifacts\training]
[2025-08-09 14:23:17,814: ERROR: main: Could not import PIL.Image. The use of `load_img` requires PIL.]
Traceback (most recent call last):
  File "main.py", line 33, in <module>
    model_trainer.main()
  File "C:\Users\ramesh\Deep learning proj\Kidney_Disease_Classification_Deep_learning\src\cnnClassifier\pipeline\stage_03_model_training.py", line 21, in main
    training.train()
  File "C:\Users\ramesh\Deep learning proj\Kidney_Disease_Classification_Deep_learning\src\cnnClassifier\components\model_training.py", line 76, in train
    self.model.fit(
  File "C:\Users\ramesh\anaconda3\envs\kidney\lib\site-packages\keras\src\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\ramesh\anaconda3\envs\kidney\lib\site-packages\keras\src\utils\image_utils.py", line 414, in load_img
    raise ImportError(
ImportError: Could not import PIL.Image. The use of `load_img` requires PIL.
[2025-08-09 14:24:49,325: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-08-09 14:24:49,341: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-09 14:24:49,341: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-09 14:24:49,341: INFO: common: created directory at: artifacts]
[2025-08-09 14:24:49,341: INFO: common: created directory at: artifacts/data_ingestion]
[2025-08-09 14:24:49,341: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-08-09 14:25:00,841: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-08-09 14:25:02,387: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-08-09 14:25:02,387: INFO: main: *******************]
[2025-08-09 14:25:02,387: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-08-09 14:25:02,403: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-09 14:25:02,403: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-09 14:25:02,403: INFO: common: created directory at: artifacts]
[2025-08-09 14:25:02,403: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-08-09 14:25:04,122: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-08-09 14:25:04,700: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-08-09 14:25:04,700: INFO: main: *******************]
[2025-08-09 14:25:04,700: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-08-09 14:25:04,700: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-09 14:25:04,716: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-09 14:25:04,716: INFO: common: created directory at: artifacts]
[2025-08-09 14:25:04,716: INFO: common: created directory at: artifacts\training]
[2025-08-09 14:25:05,952: ERROR: main: name 'scipy' is not defined]
Traceback (most recent call last):
  File "main.py", line 33, in <module>
    model_trainer.main()
  File "C:\Users\ramesh\Deep learning proj\Kidney_Disease_Classification_Deep_learning\src\cnnClassifier\pipeline\stage_03_model_training.py", line 21, in main
    training.train()
  File "C:\Users\ramesh\Deep learning proj\Kidney_Disease_Classification_Deep_learning\src\cnnClassifier\components\model_training.py", line 76, in train
    self.model.fit(
  File "C:\Users\ramesh\anaconda3\envs\kidney\lib\site-packages\keras\src\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\ramesh\anaconda3\envs\kidney\lib\site-packages\keras\src\preprocessing\image.py", line 2525, in apply_affine_transform
    if scipy is None:
NameError: name 'scipy' is not defined
[2025-08-09 14:26:13,844: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-08-09 14:26:13,860: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-09 14:26:13,860: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-09 14:26:13,860: INFO: common: created directory at: artifacts]
[2025-08-09 14:26:13,860: INFO: common: created directory at: artifacts/data_ingestion]
[2025-08-09 14:26:13,860: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-08-09 14:26:24,294: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-08-09 14:26:25,872: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-08-09 14:26:25,872: INFO: main: *******************]
[2025-08-09 14:26:25,872: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-08-09 14:26:25,888: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-09 14:26:25,888: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-09 14:26:25,888: INFO: common: created directory at: artifacts]
[2025-08-09 14:26:25,888: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-08-09 14:26:28,341: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-08-09 14:26:28,950: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-08-09 14:26:28,950: INFO: main: *******************]
[2025-08-09 14:26:28,950: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-08-09 14:26:28,966: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-09 14:26:28,966: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-09 14:26:28,966: INFO: common: created directory at: artifacts]
[2025-08-09 14:26:28,966: INFO: common: created directory at: artifacts\training]
[2025-08-09 14:34:39,864: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-08-09 16:01:11,018: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-08-09 16:01:11,033: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-09 16:01:11,033: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-09 16:01:11,049: INFO: common: created directory at: artifacts]
[2025-08-09 16:01:11,049: INFO: common: created directory at: artifacts/data_ingestion]
[2025-08-09 16:01:11,049: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-08-09 16:01:21,877: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-08-09 16:01:23,705: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-08-09 16:01:23,705: INFO: main: *******************]
[2025-08-09 16:01:23,705: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-08-09 16:01:23,705: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-09 16:01:23,705: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-09 16:01:23,705: INFO: common: created directory at: artifacts]
[2025-08-09 16:01:23,721: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-08-09 16:01:25,346: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-08-09 16:01:26,002: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-08-09 16:01:26,002: INFO: main: *******************]
[2025-08-09 16:01:26,002: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-08-09 16:01:26,002: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-09 16:01:26,018: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-09 16:01:26,018: INFO: common: created directory at: artifacts]
[2025-08-09 16:01:26,018: INFO: common: created directory at: artifacts\training]
[2025-08-09 16:09:23,510: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-08-09 16:09:23,510: INFO: main: *******************]
[2025-08-09 16:09:23,510: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-08-09 16:09:23,526: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-09 16:09:23,541: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-09 16:09:23,541: INFO: common: created directory at: artifacts]
[2025-08-09 16:12:32,709: INFO: common: json file saved at: scores.json]
[2025-08-09 16:12:32,725: INFO: common: json file saved at: scores.json]
[2025-08-09 16:12:35,615: ERROR: main: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: '']
Traceback (most recent call last):
  File "main.py", line 45, in <module>
    model_evalution.main()
  File "C:\Users\ramesh\Deep learning proj\Kidney_Disease_Classification_Deep_learning\src\cnnClassifier\pipeline\stage_04_model_evaluation.py", line 20, in main
    evaluation.log_into_mlflow()
  File "C:\Users\ramesh\Deep learning proj\Kidney_Disease_Classification_Deep_learning\src\cnnClassifier\components\model_evaluation_mlflow.py", line 60, in log_into_mlflow
    with mlflow.start_run():
  File "C:\Users\ramesh\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\fluent.py", line 350, in start_run
    active_run_obj = client.create_run(
  File "C:\Users\ramesh\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\client.py", line 275, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
  File "C:\Users\ramesh\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 131, in create_run
    return self.store.create_run(
  File "C:\Users\ramesh\anaconda3\envs\kidney\lib\site-packages\mlflow\store\tracking\rest_store.py", line 175, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
  File "C:\Users\ramesh\anaconda3\envs\kidney\lib\site-packages\mlflow\store\tracking\rest_store.py", line 56, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "C:\Users\ramesh\anaconda3\envs\kidney\lib\site-packages\mlflow\utils\rest_utils.py", line 281, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "C:\Users\ramesh\anaconda3\envs\kidney\lib\site-packages\mlflow\utils\rest_utils.py", line 213, in verify_rest_response
    raise MlflowException(
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: ''
[2025-08-09 16:22:26,555: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-08-09 16:22:26,571: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-09 16:22:26,571: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-09 16:22:26,571: INFO: common: created directory at: artifacts]
[2025-08-09 16:22:26,571: INFO: common: created directory at: artifacts/data_ingestion]
[2025-08-09 16:22:26,571: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-08-09 16:22:37,714: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-08-09 16:22:39,292: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-08-09 16:22:39,292: INFO: main: *******************]
[2025-08-09 16:22:39,292: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-08-09 16:22:39,292: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-09 16:22:39,292: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-09 16:22:39,292: INFO: common: created directory at: artifacts]
[2025-08-09 16:22:39,308: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-08-09 16:22:40,558: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-08-09 16:22:41,433: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-08-09 16:22:41,433: INFO: main: *******************]
[2025-08-09 16:22:41,433: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-08-09 16:22:41,433: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-09 16:22:41,433: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-09 16:22:41,433: INFO: common: created directory at: artifacts]
[2025-08-09 16:22:41,448: INFO: common: created directory at: artifacts\training]
[2025-08-09 16:32:20,493: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-08-09 16:32:20,509: INFO: main: *******************]
[2025-08-09 16:32:20,509: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-08-09 16:32:20,524: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-09 16:32:20,540: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-09 16:32:20,556: INFO: common: created directory at: artifacts]
[2025-08-09 16:35:18,532: INFO: common: json file saved at: scores.json]
[2025-08-09 16:35:18,548: INFO: common: json file saved at: scores.json]
[2025-08-09 16:35:26,251: INFO: builder_impl: Assets written to: C:\Users\ramesh\AppData\Local\Temp\tmp91ejb1d1\model\data\model\assets]
[2025-08-09 16:35:26,783: ERROR: main: module 'tensorflow.keras' has no attribute '__version__']
Traceback (most recent call last):
  File "main.py", line 45, in <module>
    model_evalution.main()
  File "C:\Users\ramesh\Deep learning proj\Kidney_Disease_Classification_Deep_learning\src\cnnClassifier\pipeline\stage_04_model_evaluation.py", line 20, in main
    evaluation.log_into_mlflow()
  File "C:\Users\ramesh\Deep learning proj\Kidney_Disease_Classification_Deep_learning\src\cnnClassifier\components\model_evaluation_mlflow.py", line 72, in log_into_mlflow
    mlflow.keras.log_model(self.model, "model", registered_model_name="VGG16Model")
  File "C:\Users\ramesh\anaconda3\envs\kidney\lib\site-packages\mlflow\tensorflow\__init__.py", line 222, in log_model
    return Model.log(
  File "C:\Users\ramesh\anaconda3\envs\kidney\lib\site-packages\mlflow\models\model.py", line 551, in log
    flavor.save_model(path=local_path, mlflow_model=mlflow_model, **kwargs)
  File "C:\Users\ramesh\anaconda3\envs\kidney\lib\site-packages\mlflow\tensorflow\__init__.py", line 445, in save_model
    "keras_version": keras_module.__version__,
AttributeError: module 'tensorflow.keras' has no attribute '__version__'
[2025-08-09 16:49:00,367: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-08-09 16:49:00,383: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-09 16:49:00,383: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-09 16:49:00,383: INFO: common: created directory at: artifacts]
[2025-08-09 16:49:00,383: INFO: common: created directory at: artifacts/data_ingestion]
[2025-08-09 16:49:00,383: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-08-09 16:49:10,354: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-08-09 16:49:12,588: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-08-09 16:49:12,588: INFO: main: *******************]
[2025-08-09 16:49:12,588: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-08-09 16:49:12,588: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-09 16:49:12,588: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-09 16:49:12,588: INFO: common: created directory at: artifacts]
[2025-08-09 16:49:12,604: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-08-09 16:49:14,541: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-08-09 16:49:15,244: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-08-09 16:49:15,244: INFO: main: *******************]
[2025-08-09 16:49:15,244: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-08-09 16:49:15,260: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-09 16:49:15,260: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-09 16:49:15,260: INFO: common: created directory at: artifacts]
[2025-08-09 16:49:15,260: INFO: common: created directory at: artifacts\training]
[2025-08-09 16:58:37,501: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-08-09 16:58:37,501: INFO: main: *******************]
[2025-08-09 16:58:37,501: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-08-09 16:58:37,517: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-09 16:58:37,532: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-09 16:58:37,532: INFO: common: created directory at: artifacts]
[2025-08-09 17:01:29,383: INFO: common: json file saved at: scores.json]
[2025-08-09 17:01:29,383: INFO: common: json file saved at: scores.json]
[2025-08-09 17:01:37,461: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-08-09 17:01:39,492: INFO: builder_impl: Assets written to: C:\Users\ramesh\AppData\Local\Temp\tmpy7g4fts0\model\data\model\assets]
[2025-08-09 17:02:31,475: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
